pipeline{
    agent any

    parameters{
        booleanParam(defaultValue: false, description: "Enable Service", name: "myBoolean")
    }

    stages{
        stage("Demo"){
            steps{
                echo "booleanParam s set to ${params.myBoolean}"
            }
        }
    }
}